name: 'build and deploy production'

on:
  push:
    tags:
      - '*'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        name: Set nodejs version to 18.x
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - run: npm ci

      - name: Run build production (create dist folder)
        run: npm run build
