name: 'CI'

on:
  push:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        name: Set nodejs version to 18.x
        with:
          node-version: '18.x'

      - run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format
  unitttest-job:
    runs-on: ubuntu-latest
    needs: lint-job
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        name: test on ${{ matrix.os }} nodejs version ${{ matrix.node-version}}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - run: npm ci

      - name: Run Unit Test
        run: npm run test:unit